[package]
name = "hello_world"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "./src/rust/lib.rs"

[dependencies]
js-sys = "0.3.28"
cached = "0.9.0"

[dependencies.wasm-bindgen]
version = "^0.2"
